### ISSUE TITLE
How to enter actual slack client?

### ISSUE THREAD

**Issue by alex-popov-tech** [Colmbus72/slim#1]
I did all as in README, after `:W` there is a check and a `W` sign to the left of my workplace, but how do i enter actual client?

**Comment by Colmbus72** [comment]
After you run `:W` and see that W on the line next to your token. The next time you run `:Slack` it will open the client

**Comment by alex-popov-tech** [comment]
it just opens same buffer instead of slack client...can you make a screen of which id should i provide? I'm not sure i set right token through

**Comment by Colmbus72** [comment]
Under `https://api.slack.com/apps/<app_id>/oauth?` should be an OAuth access token in the format `xoxp-...` 

Can you verify that there is a file named `app_state.vim` under the `.data/` dir in your bundle?

**Comment by alex-popov-tech** [comment]
oh...i need to receive an request approval for generating that token, probably i put wrong one initially, maybe nothing to do with a plugin, closing until i will have a token and try again
