### ISSUE TITLE
Apostrophes break a message

### ISSUE THREAD

**Issue by igbanam** [Colmbus72/slim#2]
I must start with **"This is an AMAZING tool!"**. Thank you 🙇 

I have tried my hands out on it and I have a couple issues to surface.

When I compose a message like "Don't worry about it", what gets transmitted is "Don". It would be nice to get the entire message transmitted. I think it has something to do with escaping the strings being sent to Slack? I dunno.

My vimscript-fu is still at beginner level else I'd have had this fixed

**Comment by Colmbus72** [comment]
Glad to hear you enjoy it! I did a little digging and you're right it is something to do with how the strings are being escaped when going to the curl request.

I will try to get a fix in soon

**Comment by igbanam** [comment]
Hi, just checking if you got around to fixing this. Maybe you could point me in the right direction. I don't mind contributing to the repository.

**Comment by igorlima** [comment]
hello @igbanam - I faced the issue 😞 

to bypass apostrophes breaks a message, it was needed to avoid the usage of `eval`
- https://github.com/Colmbus72/slim/pull/4

hope it helps you the way it's helping me
