### ISSUE TITLE
How to view channels

### ISSUE THREAD

**Issue by igbanam** [Colmbus72/slim#3]
So far, only the DM list is showing up. How can one refresh the channels list? I have the `channels:read` permission setup as it should.

**Comment by Colmbus72** [comment]
Do you also have `channels:history` setup for the token as well?

**Comment by igbanam** [comment]
Yes, I have `channels:history`. My full permissions list is 

```
channels:history
channels:read
chat:write
groups:history
groups:read
im:history
im:read
mpim:history
mpim:read
team:read
users:read
```

**Comment by igbanam** [comment]
Hi, did you get some time to check this out?

**Comment by igorlima** [comment]
try to have a token from this method 4:
- https://github.com/erroneousboat/slack-term/wiki#method-4

I didn't face any issue anymore by using that token 

hope it helps

**Comment by Colmbus72** [comment]
@igbanam So far I have been unable to recreate the issue. Are you still experiencing this?
