### ISSUE TITLE
Feature request: GUI for chat

### ISSUE THREAD

**Issue by bbauman1** [Colmbus72/slim#5]
this is a cool chat app in the terminal, but have you considered making a UI for this app? maybe with electron  @Colmbus72

**Comment by Colmbus72** [comment]
Hey @bbauman1! This project is actually a plugin for a program called vim. You are correct it is used in the terminal however it is something that is generally used by programmers to code. If you're interested in electron I would suggest checking out atom or vs code, which both are written in. As for the electron version of slim i'd checkout this companies app: https://apps.apple.com/app/slack/id803453959
